CREATE DATABASE LIVRARIA;

CREATE TABLE LIVROS(
    NOME_DO_LIVRO VARCHAR(50),
    NOME_DO_AUTOR VARCHAR(30),
    SEXO_DO_AUTOR CHAR(1),
    NUMERO_DE_PAGINAS INT(10),
    NOME_DA_EDITORA VARCHAR(30),
    VALOR_DO_LIVRO VARCHAR(5),
    ESTADO_UF_DA_EDITORA CHAR(2),
    ANO_DE_PUBLICAÇÃO CHAR(4)
);

INSERT INTO LIVROS (NOME_DO_LIVRO,
NOME_DO_AUTOR,
SEXO_DO_AUTOR,
NUMERO_DE_PAGINAS,
NOME_DA_EDITORA,
VALOR_DO_LIVRO,
ESTADO_UF_DA_EDITORA,
ANO_DE_PUBLICAÇÃO
) VALUES(
    'Cavaleiro Real',
    'Ana Claudia',
    'F',
    465,
    'Atlas',
    49.9,
    'RJ',
    2009
);

SELECT NOME_DO_LIVRO, NOME_DA_EDITORA FROM LIVROS;

SELECT NOME_DO_LIVRO, NUMERO_DE_PAGINAS FROM LIVROS WHERE SEXO_DO_AUTOR='M';
SELECT VALOR_DO_LIVRO, FROM LIVROS WHERE ESTADO_UF_DA_EDITORA='SP';

SELECT NOME_DO_AUTOR, SEXO_DO_AUTOR
FROM LIVROS
WHERE SEXO_DO_AUTOR = 'M'
AND ESTADO_UF_DA_EDITORA = 'SP'
OR ESTADO_UF_DA_EDITORA = 'RJ';