/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO DE DADOS */

USE PROJETO;

/* CRIANDO TABELA CLIENTES */

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);


/* VERIFCANDO TABELAS NO BANCO DE DADOS  */

SHOW TABLES;


/* DESCOBRINDO A ESTRUTURA DE UMA TABELA*/

DESC CLIENTE;

/* Inserindo tabelas no banco de dados! */

INSERT INTO CLIENTE (NOME,EMAIL,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIANE','liliane@gmail.com','F', 'RUA 2017 SETOR NOVO HORIZONTE','62982490118', 06597322118)
INSERT INTO CLIENTE (NOME,EMAIL,SEXO,ENDERECO,TELEFONE,CPF) VALUES('Mateus','mateusfl@gmail.com','M', 'RUA 2014 PORTAL DOS SONHOS','62965650118', 123432567)
INSERT INTO CLIENTE (NOME,EMAIL,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LUCAS','lucasferreira@gmail.com','M', 'RUA MORASA SETOR LAGO AZUL','62986540118', 758340868)

/* Exibindo dados! */

SELECT NOME, SEXO, EMAIL FROM CLIENTE
SELECT NOME as CLIENTES, SEXO, EMAIL FROM CLIENTE

/* NAO USE SELECT * FROM CLIENTES*/

SELECT * FROM CLIENTES

O Filtro nao filtra em coluna, ele filtra em linha.

SELECT NOME, ENDERECO FROM CLIENTE WHERE SEXO = 'F';

Banco de dados = Teoria dos Conjuntos!

/* Tradução do comando acima: projete a tabela nome e endereço onde
o sexo for igual a F (f no caso, feminino) */


SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE ENREDECO LIKE '%RJ'

/* Tradução do comando acima: PROJETE PARA MIM A TABELA NOME, SEXO
ENDEREÇO DO BANCO DE DADOS CLIENTE, ONDE O ENDEREÇO COMEÇA COM QUALQUER
COISA '% É O CARACTERE CORINGA' E TERMINA COM RJ*/

Não esqueça do "caractere coringa" que é o %


Comandos do exercicio:

SELECT * FROM LIVROS

SELECT COUNT(*) AS 'QUANTIDADE DE REGISTROS NA TABELA LIVROS' FROM LIVROS:

SELECT SEXO_DO, COUNT(*) FROM LIVROS, GROUP BY SEXO;