/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO DE DADOS */

USE PROJETO;

/* CRIANDO TABELA CLIENTES */

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);


/* VERIFCANDO TABELAS NO BANCO DE DADOS  */

SHOW TABLES;


/* DESCOBRINDO A ESTRUTURA DE UMA TABELA*/

DESC CLIENTE;/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO DE DADOS */

USE PROJETO;

/* CRIANDO TABELA CLIENTES */

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);


/* VERIFCANDO TABELAS NO BANCO DE DADOS  */

SHOW TABLES;


/* DESCOBRINDO A ESTRUTURA DE UMA TABELA*/

DESC CLIENTE;

/* Inserindo tabelas no banco de dados! */

INSERT INTO CLIENTE (NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIANE','F', 'RUA 2017 SETOR NOVO HORIZONTE','62982490118', 06597322118)